version: '2'
services:
  realestate:
    environment:
      NODE_ENV: development-local
      MONGODB_CONNECTION_STRING: "mongodb://real-db:27017/real"
      MONGODB_DEBUG: "true"
    build: .
    working_dir: /var/app
    volumes:
     - .:/var/app
    depends_on:
      - "real-db"
    networks:
      - default
      - bnotesnet
  real-db:
    image: "mongo:3.4.0"
    ports:
     - "27021:27017"

networks:
  bnotesnet:
    external: true